sonar.projectKey=ltm-dashboard
sonar.projectName=LTM Dashboard
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,out/**,public/**,deployment/**,docs/**,_specification/**,scripts/**,**/*.config.*,next-env.d.ts,**/*.d.ts,.scannerwork/**

sonar.typescript.tsconfigPaths=tsconfig.json
