environment: val

replicaCount: 2

image:
  repository: r-2k77-devops-docker-releases-local.artifactory.fr.eu.airbus.corp/hosting/fits/val/nextjs-hello-image
  pullPolicy: IfNotPresent

nextjs:
  application:
    base: "/app-f1fd/nextjs-hello/"
    port: "8080"

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: nextjs-hello-val.f1fd-fits.airbus.corp
      paths:
        - path: /app-f1fd/nextjs-hello
          pathType: Prefix
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

resources:
  limits:   { cpu: 300m, memory: 256Mi }
  requests: { cpu: 100m, memory: 128Mi }
