environment: dev

deployment:
  name: nextjs-hello
  service: svc

replicaCount: 2

image:
  repository: nextjs-hello
  tag: "0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  name: http
  port: 80
  targetPort: 8080

nextjs:
  application:
    base: "/"
    port: "8080"

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: hello.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

probes:
  enabled: true
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
volumes:
  - name: nginx-conf-d
    emptyDir: {}
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}

volumeMounts:
  - name: nginx-conf-d
    mountPath: /etc/nginx/conf.d
  - name: nginx-cache
    mountPath: /var/cache/nginx
  - name: nginx-run
    mountPath: /var/run
